parsers:
  "**/*.cjs": "es6"
  "**/*.mjs": "es6"
  "**/*.ts": "typescript"
ignores:
  - "@commitlint/*"
  - "@repobuddy/jest"
  - "@semantic-release/*"
  - "@size-limit/preset-small-lib"
  - "@types/node"
  - "@types/jest"
  - jest-*
  - semantic-release
  - ts-jest
  - ts-loader
  - tslib
  - webpack-cli
