ignores:
  - "@commitlint/*"
  - "@semantic-release/*"
  - "@size-limit/preset-small-lib"
  - '@types/node'
  - "@types/jest"
  - babel-jest
  - colormap
  - jest-*
  - param-case
  - pascal-case
  - semantic-release
  - ts-jest
  - ts-loader
  - tslib
  - webpack-cli
